version: "3.8"

services:
  app:
    container_name: prasetia-revops-hub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    restart: always
    # environment:
    #   - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.revops-web-router.rule=Host(`revops.virtuenet.space`)"
      - "traefik.http.routers.revops-web-router.entrypoints=https"
      - "traefik.http.routers.revops-web-router.tls.certresolver=letsencrypt"
      - "traefik.http.routers.revops-web-router.priority=100"
      - "traefik.http.services.revops-web-service.loadbalancer.server.port=80"
    networks:
      - coolify

networks:
  coolify:
    external: true
